### ISSUE TITLE
Usage of calibration

### ISSUE THREAD

**Issue by VasilevIvanVladimirovich** [PBernalPolo/triaxialSensorCalibration2019#1]
Hi @PBernalPolo , 
It 's me again 😊.
I want to try using your algorithm, but I don't have a servo for the temperature chamber. Can I use my robot arm to calibrate the IMU in a room environment ?

It is expected that I plan to apply calibration in the same environment.

At the moment I am interested in the possibility of calibration and application of IMU calibration.

**Comment by pbernalpolo** [comment]
Hi @VasilevIvanVladimirovich ,

you can use whatever works for you. The key is to have a rich enough set of calibration data. It does not matter if you use a servo, a robot arm, or you do it yourself manually (although I would not recommend that last option because it would be error prone and really boring). For the accelerometer you will need a bunch of measurements taken in static conditions. For all of them you will be measuring 1g. For the gyroscope you will need to provide a known angular velocity in different orientations. Note that if you make the last articulation of your robot arm spin, this won't provide a rich set of calibration data; the IMU will only measure the angular velocities around a single axis. You will need to make the most external articulation spin, and change the orientation with at least 2 inner articulations (you need at least 2 degrees of freedom to reach all the possible directions in R3).

On the other hand, it is ok to not use a temperature chamber. Preparing one requires of quite an effort. And if you want to just test the algorithm, then it is better to keep the effort low. However, note that there will be a lot of agents affecting the temperature of your sensor:
- it will heat up at initialization,
- if you touch it, this will change the temperature significantly,
- different orientations will create different air flows that will change the temperature of the sensor,
- if you use it in different days, your room temperature will be different.
However, for the algorithm I designed you don't need to keep a constant temperature. You can collect samples at different temperatures, and the result will be a calibration in which each component has a polynomial dependence on the temperature.

**Comment by VasilevIvanVladimirovich** [comment]
Thank you for such a detailed answer.
It looks like your calibration is really universal. I am glad that I can not use the temperature chamber for my tests.
