### ISSUE TITLE
Default calibration

### ISSUE THREAD

**Issue by VasilevIvanVladimirovich** [PBernalPolo/triaxialSensorCalibration2019#3]
Good afternoon

I am puzzled by the function GyroscopeCalibrator.pde
https://github.com/PBernalPolo/triaxialSensorCalibration2019/blob/cd0205352221f7bad3cf26d74fca69937d36331d/temperatureCalibrationAlgorithm/GyroscopeCalibrator.pde#L43-L72
  
The comment says that these values are taken from the IMU documentation.
`  // computes the error using the default calibration (the one presented in the datasheet)`

I assume these values are the full scale:
Gyro: +-2000 dps
Acc: +-16 g

Then why in the code is the gyroscope 1/16.4 
and the accelerometer 1/2048?

I don't understand why these values are here.

**Comment by pbernalpolo** [comment]
Hi @VasilevIvanVladimirovich ,

you can find information about each one of the IMUs I calibrated during my PhD in Table 6.1 of https://digitum.um.es/digitum/bitstream/10201/95443/1/Pablo%20Bernal%20Polo%20Tesis%20Doctoral.pdf
In particular, for the case of sensors with ID 11, 13, 14 and 15 we have an MPU6050. Find its datasheet in the following link:
https://invensense.tdk.com/wp-content/uploads/2015/02/MPU-6000-Datasheet1.pdf
If you go to section 6.1 Gyroscope Specifications, you will find that for +-2000 dps we have 16.4 LSB(dps). This fits what we expect, because
```
2000dps/2^15(LSB) = 1/(2^15(LSB)/2000dps)
                  = 1/16.384 dps/LSB
```
where we used `2^15` because the MPU6050 is a 16-bit sensor, so we have 1 bit for the sign, and 15 bits for the value. Since raw sensor readings are obtained as an integer ranging from -2^15 to 2^15-1, we need to divide by 2^15 to fit the values from -1 to 1, and then multiply by the full-scale value to obtain the measurement in the appropriate units. If you check section 6.2 you will find the information relative to the accelerometer.

The sensor with ID 12 is a MPU9250. Here is the datasheet:
https://invensense.tdk.com/wp-content/uploads/2015/02/PS-MPU-9250A-01-v1.1.pdf
and you can find the information we are looking for in section 3.1. We have the same situation as above.

And the same happens for the other sensors:
- ID 16 is L3GD20H:
https://pdf1.alldatasheet.com/datasheet-pdf/view/929243/STMICROELECTRONICS/L3GD20H.html (see section 2.1)
- ID 17 is LSM9DS1:
https://cdn.sparkfun.com/assets/learn_tutorials/3/7/3/LSM9DS1_Datasheet.pdf (see section 2.1)

**Comment by VasilevIvanVladimirovich** [comment]
Thank you, you helped me a lot
