### ISSUE TITLE
Kalman filter

### ISSUE THREAD

**Issue by VasilevIvanVladimirovich** [PBernalPolo/triaxialSensorCalibration2019#4]
Hello ) 
I noticed that you rewrote the kalman filter in the [IM_IMO class](https://github.com/PBernalPolo/triaxialSensorCalibration2019/blob/master/calibrationTestD/IM_IMU.java) in the update function. Here you first look for new calibrated values, and then use them in the implementation of a kalman filter other than [test_MKF](https://github.com/PBernalPolo/test_MKF/blob/master/test_MKF/MEKF.java).

Are these kalman filter implementations equal ?

If I get new calibrated accelerometer and gyroscope values using the function:
https://github.com/PBernalPolo/triaxialSensorCalibration2019/blob/cd0205352221f7bad3cf26d74fca69937d36331d/calibrationTestD/TriaxialCalibration.java#LL108C1-L119C3

Сan I use them as input to:
https://github.com/PBernalPolo/test_MKF/blob/29c46e17ddc709b18a2365e2c1746f7e78be5c51/test_MKF/MEKF.java#L30

**Comment by VasilevIvanVladimirovich** [comment]
Actually, why I'm asking this question:
I took your calibration [dataset ](https://github.com/PBernalPolo/triaxialSensorCalibration2019/blob/master/temperatureCalibrationAlgorithm/storedData/data_20190530163305.dat)for a sensor with an index of 17 and visualized the rotation of the object using the output quaternion of the Kalman filter.

The first object on the gif is the MEKFcRP quaternion, the second object rotates using the Kalman quaternions of the TriaxialCalibration implementation filter (before using, I commented out the calibration application lines). The picture shows that the blue green axis has changed its sign. I use the raw data obtained from the accumulation of data for calibration
![TestKalman](https://github.com/PBernalPolo/triaxialSensorCalibration2019/assets/65816571/734a79ee-9f42-431f-bf4f-27dc3ca4a3cc)

**Comment by pbernalpolo** [comment]
Hi!

let me list the datasheets with a particular page associated to each one of them:
- ID 11, 13, 14, 15 (page 21)
https://invensense.tdk.com/wp-content/uploads/2015/02/MPU-6000-Datasheet1.pdf
- ID 12 (page 38)
https://invensense.tdk.com/wp-content/uploads/2015/02/PS-MPU-9250A-01-v1.1.pdf
- ID 16 (page 9, and page 8 in second document)
https://www.sparkfun.com/datasheets/Sensors/Magneto/LSM303%20Datasheet.pdf
https://www.pololu.com/file/0J731/L3GD20H.pdf
- ID 17 (page 10)
https://cdn.sparkfun.com/assets/learn_tutorials/3/7/3/LSM9DS1_Datasheet.pdf

In each page you will see the axis in which measurements are expressed for each sensor. In particular, you will note that every sensor expresses its measurements in a right-handed reference frame (which is the standard in which i x j = k with i the unit vector in the x direction, j the unit vector in the y direction, and k the unit vector in the z direction), except for the sensor with ID 17. In that case acceleration and angular velocity measurements are expressed in a left-handed reference frame. Most probably, just by using a default calibration for the sensor with ID 17 the plots will start to look more similar. However, I think that the implementations may still differ in the magnitude of the gravity vector. If you check line 22 in
https://github.com/PBernalPolo/triaxialSensorCalibration2019/blob/master/calibrationTestD/IM_IMU.java
and line 26 in
https://github.com/PBernalPolo/test_MKF/blob/master/test_MKF/MEKF.java
you will see that gravity is expressed in [m/s²] in the first, but in [g] in the second. So in order to make a correct comparison you will need to transform acceleration measurements differently for each piece of code.

As a conclusion, I would use a different dataset to be sure that the left-handed reference frame problem is not playing a role. And please, tell me if this solves the problem! :)

Another thing that I noticed is that the sensors containing magnetometers (IDs 12, 16, 17) use a different reference frame than the accelerometers and gyroscopes (except for ID 16). I remember that I was having problems to use magnetometer measurements to obtain a full orientation estimation. I will check in the far future if the reference frame definition had something to do with it...

**Comment by VasilevIvanVladimirovich** [comment]
Hi

I decided to follow your advice and try a different data set and took sensor 11 for this.  I didn't use calibration to compare kalman filters.

I expect to get data from the accelerometer in the format G = raw data * 1/2048;
From the gyroscope I expect to get radians/second = raw data * PI/180*1/16;

I will use these values as input values of the java implementation of MEKFcRP and IM_IMO(cRP)


[data_20(...).dat](https://github.com/PBernalPolo/triaxialSensorCalibration2019/blob/master/temperatureCalibrationAlgorithm/storedData/data_20190530163305.dat) -> first line for id 11:
`0 11 1609 -12 1313 8 0 -15 -4672 -117 -706 276 0.0`

MEKFcRP at the input (acc - g, gyr - rad/s)
IM_IMO(cRP) at the input  (acc - g, gyr - rad/s)
acc [0] = 1609 -> 0,78564453125 g
gyr [0] = 8 ->0,00875 rad/s
dt = 0.02 sec

I get different quaternions at the output, although knowing that the implementation of the Kalman filter is the same, I expect to get the same values.

the first quaternion of MEKFcRP
`0.9307727558014542 -0.002726564677210799 -0.36558804804106004 -1.4843299893368606E-4`
the first quaternion is IM_IMO(cRP)
`0.9991975624139782 -0.002987078172076227 -0.04005173982392208 -1.3292139742397457E-5`

I have tried many times to achieve the result by changing the input data, but it was not successful. It seems to me that the implementation of kalman filters is different in MEKFcRP and IM_IMO(cRP), or I don't understand something.

In the video
on the left - MEKFcRP 
right - IM_IMO(cRP)

![CompareKalman](https://github.com/PBernalPolo/triaxialSensorCalibration2019/assets/65816571/755c95ee-a86d-4683-aa46-1989d1aad6ab)

**Comment by pbernalpolo** [comment]
Hi @VasilevIvanVladimirovich ,

note that the acceleration should be introduced in [m/s^2] in the case of the IM_IMU. Also, I don't remember exactly about the exact value for dt, but should be around 0.005. However, it is really difficult to choose a correct value because the data was pre-filtered when it was being collected. In particular, the calibration system would stop sending data if the turntable was moving to a new orientation. Then, we will find in the dataset measurements taken with a time difference of about 0.005 seconds, while in some particular cases the measurements could be taken with a time difference of about 2 seconds!

Regarding the different quaternions at the output, note that you will most likely never obtain exactly the same values. There are multiple reasons for this:
- The tuning parameters for each filter may be different. In fact, just checking the value for the covariance that describes the acceleration noise:

https://github.com/PBernalPolo/test_MKF/blob/29c46e17ddc709b18a2365e2c1746f7e78be5c51/test_MKF/OrientationEstimator.java#L41

https://github.com/PBernalPolo/triaxialSensorCalibration2019/blob/cd0205352221f7bad3cf26d74fca69937d36331d/calibrationTestD/IM_RigidBody.java#L57

we observe that they have different values.
- We do not have an absolute reference for attitude; we only observe the direction of gravity. Then, any small difference will lead to totally different quaternions due to different heading estimations (for which there is no absolute observation).
- Even if the implementations look very similar, and the tuning parameters are chosen to be the same, the implementations will most probably differ in the order in which some computation is made. For example, `(1.0/3.0*1.0/5.0)*1.0/7.0-(1.0/3.0*(1.0/5.0*1.0/7.0))` should output 0.0, but in Java we obtain `-1.734723475976807E-18`.
- There could be even more differences in the implementation. I don't remember the precise details for each one of them. Note that I uploaded these files 4 years ago...

I would advice you to set up your own IMU. It is usually really simple to interface them with an Arduino and obtain your own measurements. This way you will be able to test the algorithms in real time :)

**Comment by VasilevIvanVladimirovich** [comment]
Hi @PBernalPolo 
For some reason I thought that by default these filters have the same parameters, it looks like I was wrong. Thank you for clarifying this point.

I really want to understand your calibration and learn how to calibrate my IMU, but I was alerted by the moment of differences in the work of these two kalman filters, thanks to you I understood what was going on and I can study further.
