### ISSUE TITLE
Accumulation of IMU data

### ISSUE THREAD

**Issue by VasilevIvanVladimirovich** [PBernalPolo/triaxialSensorCalibration2019#5]
Hi @PBernalPolo 

I did not find detailed guidance in your scientific article, so I drew my conclusions about this process from a video on YouTube.

I want to make sure that my understanding of the IMU data accumulation process is correct:

- Accumulation occurs both in a stationary state and in motion. The stationary state is necessary for the calibration of the accelerometer, and the movement is necessary for the calibration of the gyroscope.
- It turns out the position of the system should consist of alternating stationary positions and movements
- Movements for one pose should be recorded with a known angular velocity relative to one orientation. clockwise with positive angular velocity, counterclockwise with negative angular velocity
- Movement postures should differ from each other and be in different orientations to provide a more extensive data set
- When changing orientation, data should not be recorded
- Make a run of the sensor's IMU positions for each temperature unit (for example - I expect my IMU to work in the temperature range (-40*C; +55*C) so I will run my positions for each degree Celsius (95 repetitions))

In order not to get confused, I would also like to approve the units of measurement to perform calibration:
- angular velocity - radians/second
- temperature - degree Celsius (*C)
- accelerometer - g
- gyroscope - radians/second

If I misunderstood something, please correct me 😊

**Comment by pbernalpolo** [comment]
Hi @VasilevIvanVladimirovich ,

first of all, let me compile the different sources of information about this topic:
**Conference paper**: https://www.researchgate.net/profile/Pablo-Bernal-Polo/publication/321976493_Triaxial_Sensor_Calibration_A_Prototype_for_Accelerometer_and_Gyroscope_Calibration/links/607f4972907dcf667bb10e4a/Triaxial-Sensor-Calibration-A-Prototype-for-Accelerometer-and-Gyroscope-Calibration.pdf
**Journal paper**: https://www.researchgate.net/publication/336340489_Temperature-Dependent_Calibration_of_Triaxial_Sensors_Algorithm_Prototype_and_Some_Results
**PhD thesis** (chapter 6): https://digitum.um.es/digitum/bitstream/10201/95443/1/Pablo%20Bernal%20Polo%20Tesis%20Doctoral.pdf
**Youtube video**: https://www.youtube.com/watch?v=Z5JtIe8469I

And now, let me continue not correcting, but adding comments to your notes:

> Accumulation occurs both in a stationary state and in motion. The stationary state is necessary for the calibration of the accelerometer, and the movement is necessary for the calibration of the gyroscope.

I agree with this, but I would better say that the accelerometer needs to measure gravity, and this is why it needs to collect measurements in a static position. On the other hand the gyroscope needs to measure a known angular velocity. This is why it ideally needs to collect measurements at a constant angular velocity.

> It turns out the position of the system should consist of alternating stationary positions and movements

This is the way I did it, but it is not mandatory. I thought that it would be nice to collect gyroscope measurements at different angular velocities starting from no angular velocity and increasing it in steps. Then I would take advantage of the zero angular velocity measurements to calibrate the accelerometer. However, other person could think about other measurement collection process.

> Movements for one pose should be recorded with a known angular velocity relative to one orientation. clockwise with positive angular velocity, counterclockwise with negative angular velocity

This is true for other calibration algorithms. But since the one I developed is based on minimizing the distance to the squared norm of the measured vector (which is invariant under rotations), it is not necessary to know the expression of the vector in the sensor reference frame, nor the direction of rotation; only the modulus of the vector (g for accelerometers, and the known angular velocity for gyroscopes). In the video you will note that sometimes the turntable spins in a direction, and other in the opposite direction. This is just a way to diversify the measured vectors, but the algorithm does not need to know the rotation direction.

> Movement postures should differ from each other and be in different orientations to provide a more extensive data set

I agree with this statement as it is. I will reference here Appendix B.1 of my PhD thesis. There you can see a lot of examples of collected data, and you will note how rich the datasets are. On the other hand, you can check Figures 3 and 4 on the conference paper listed above. The calibration system I had at that time was not as good as the one I ended up designing; in the first one I was not able to collect vector measurements in all directions, and that led to lower quality calibrations.
Another interesting part of this paper is Figure 6. There the limitations of the algorithm become visible (the algorithm does not estimate non-linear scale factors).

> When changing orientation, data should not be recorded

Either that, or one stores a flag that indicates that the sensors are moving, and then use that flag to discard the measurements before introducing them to the algorithm. This is necessary in order to prevent accelerations due to a movement to be added to the gravity vector (which is the vector whose modulus we know), or to prevent angular velocities due to a movement to be added to the known angular velocity provided by the motor. The case of a magnetometer is different, because rotation do not affect the measured magnetic field (actually they do, but the reason is different; a rotation produces a change in the geometrical configuration of the material surrounded by the magnetic field, and that produces a modification of the magnetic field. This makes magnetometer calibration less precise. Actually, due to the same reason, I couldn't calibrate magnetometers in the rotation table; there was too much iron around the sensor, and this produced significant changes in the distribution of the magnetic field, and ultimately a non-homogeneous magnetic field).

> Make a run of the sensor's IMU positions for each temperature unit (for example - I expect my IMU to work in the temperature range (-40C; +55C) so I will run my positions for each degree Celsius (95 repetitions))

This is not necessary. The algorithm I present in the journal paper has a big advantage in this regard. If you check the figures in Appendix B.1 in my PhD thesis, or in the journal paper, you will see that all the measurements are introduced with the temperature the sensor had at each moment. It was not necessary to collect measurements in a given temperature. In fact, since I had to calibrate magnetometers rotating them by hand so that they were not surrounded by iron, I modified the temperature by blowing at them (check the temperature figures of Appendix B.1).
Now, although given the properties of the algorithm you don't have constraints with regard to temperature (we just need a value for it), it will be necessary to change temperature slowly (so that the measured temperature is representative of the temperature of the sensor, and there is not a spacial gradient of temperature over the sensor package), and to collect measurements in the operation temperature range (otherwise we will not have information about the calibration for some temperature values in the range of operation, and the value returned by the calibration will be an extrapolation that won't usually accurately describe the sensor behavior).

Finally, regarding the units, it is only necessary to provide the units for the known vectors. So for the case of the accelerometer you will need to provide either 1g or ~9.8m/s. In the case of the gyroscope, you will need to provide an angular velocity and feed the known values to the algorithm either in rad/s or in deg/s. Consider in both cases that the calibrated measurements will be outputted with the same units that you introduce for the modulus of the known vector. For the measurements, you can make an initial transformation in order to give an estimation from the default calibration in the units that you want in each case. However, this is not necessary. In my case, I introduced the values to the algorithm as row values. As an example, for a 16bit sensor it will measure values in the range `[ −32768 , 32767 ] = [ −2^15 , 2^15 − 1 ]`. Those raw values were the ones I introduced, and the algorithm takes care of transforming this raw values to values in the units provided by the known vector estimating scale factors, biases...
